//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartments()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public string apmtID { get; set; }
        public string apmtDescription { get; set; }
        public decimal apmtPrice { get; set; }
        public string apmtType { get; set; }
        public string apmtStatus { get; set; }
        public string apmtImg { get; set; }
        public string landlordID { get; set; }
    
        public virtual Landlords Landlords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
