//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public string petID { get; set; }
        public string petName { get; set; }
        public string petSpecies { get; set; }
        public string petBreed { get; set; }
        public int petAge { get; set; }
        public string petGender { get; set; }
        public string petStatus { get; set; }
        public decimal petPrice { get; set; }
        public byte[] petImage { get; set; }
    }
}
