//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public string transactionID { get; set; }
        public string userID { get; set; }
        public string petID { get; set; }
        public decimal totalPayment { get; set; }
        public decimal amountCustPay { get; set; }
        public decimal payChange { get; set; }
        public Nullable<System.DateTime> transDate { get; set; }
    }
}
