//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllApartment
    {
        public string Apartment_ID { get; set; }
        public string Apartment_Description { get; set; }
        public string Good_for___Person { get; set; }
        public string Status { get; set; }
        public string Image { get; set; }
    }
}
