//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BuyPet
    {
        public string Pet_ID { get; set; }
        public string Pet_Species { get; set; }
        public string Pet_Breed { get; set; }
    }
}
