//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employees
    {
        public string User_ID { get; set; }
        public string Username { get; set; }
        public string Role_Type { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.DateTime> Account_Date_Created { get; set; }
    }
}
