//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PetAvailable
    {
        public byte[] Pet_Image { get; set; }
        public string Pet_ID { get; set; }
        public string Pet_Name { get; set; }
        public string Species { get; set; }
        public string Breed { get; set; }
        public int Pet_Age { get; set; }
        public string Gender { get; set; }
        public string Pet_Status { get; set; }
        public decimal Pet_Price { get; set; }
    }
}
