//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hubitat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransactionReports
    {
        public string Transaction_ID { get; set; }
        public string User_ID { get; set; }
        public string User_Name { get; set; }
        public string Email { get; set; }
        public string Pet_ID { get; set; }
        public string Pet_Name { get; set; }
        public string Pet_Species { get; set; }
        public string Pet_Breed { get; set; }
        public decimal Total_Payment { get; set; }
        public decimal Amount_Pay { get; set; }
        public decimal Change_Amount { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
    }
}
